### ISSUE TITLE
Some questions about your netR_36.model

### ISSUE THREAD

**Issue by StiphyJay** [HaozheQi/P2B#11]
Hello, thanks for you job.
       I want to know that weather the model(netR_36.model) is trained in two GTX1080Ti gpu? if you are, when i want to test this model in a machine with one GTX1080Ti, this model could weather or not work?  When i test it, there are some error in my terminal.
I have modified  the code in test_tracking.py when i test.
parser.add_argument('--ngpu', type=int, default=1, help='# GPUs') 
os.environ["CUDA_VISIBLE_DEVICES"] = '0' 
 the error is:
Traceback (most recent call last):
  File "test_tracking.py", line 177, in <module>
    netR.load_state_dict(torch.load(os.path.join(args.save_root_dir, args.model)))    
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pointnet_Tracking:
 
I would appreciate it if you could reply. Thank you!

**Comment by AmingWu** [comment]
@StiphyJay , Do you download the label_02 dataset? Whether the dataset only contains the training set.

**Comment by StiphyJay** [comment]
> @StiphyJay , Do you download the label_02 dataset? Whether the dataset only contains the training set.

Yes,I download the label_02 dataset, and my dataset directory only contains testing set(0019,0020). Is it possible that the problem with the model caused the operation error?

**Comment by HaozheQi** [comment]
Hi, @StiphyJay, yes, the netR_36.model is trained with two gpus to speed up the training phase. But I don't know how to run the model trained with two gpus on a single gpu in Pytorch. In practice, the model trained with two gpus will be tested using two gpus as well.
This is a suboptimal solution. If you can figure out this problem, I would appreciate for you sharing.

**Comment by StiphyJay** [comment]
> Hi, @StiphyJay, yes, the netR_36.model is trained with two gpus to speed up the training phase. But I don't know how to run the model trained with two gpus on a single gpu in Pytorch. In practice, the model trained with two gpus will be tested using two gpus as well.
> This is a suboptimal solution. If you can figure out this problem, I would appreciate for you sharing.

Thanks for your reply. Here is my new question? Could you help me solve it?
Traceback (most recent call last):
  File "test_tracking.py", line 178, in <module>
    netR.load_state_dict(torch.load(os.path.join(args.save_root_dir, args.model)))    
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.vote_layer.0.conv.weight: copying a param with shape torch.Size([256, 259, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 1]).

**Comment by HaozheQi** [comment]
I think you might change the original code [here](https://github.com/HaozheQi/P2B/blob/master/pointnet2/models/pointnet_tracking.py#L120).
