### ISSUE TITLE
testing problem

### ISSUE THREAD

**Issue by freshwk** [HaozheQi/P2B#24]
hi! when i run test_tracking.py,the following error occurred：

Namespace(IoU_Space=3, category_name='Car', data_dir='./data/training', model='netR_36.pth', model_fusion='pointcloud', ngpu=1, reference_BB='previous_result', save_root_dir='./model/car_model/', shape_aggregation='firstandprevious')
Traceback (most recent call last):
  File "/home/wangkai/P2B/test_tracking.py", line 176, in <module>
    netR.load_state_dict(torch.load(os.path.join(args.save_root_dir, args.model)))    
  File "/home/wangkai/anaconda3/envs/py1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Pointnet_Tracking:
	Missing key(s) in state_dict: "backbone_net.SA_modules.0.mlps.0.layer0.conv.weight", "backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.weight", "backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.bias", "backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.running_mean", "backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.running_var", "backbone_net.SA_modules.0.mlps.0.layer1.conv.weight", "backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.weight", "backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.bias", "backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.running_mean", "backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.running_var", "backbone_net.SA_modules.0.mlps.0.layer2.conv.weight", "backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.weight", "backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.bias", "backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.running_mean", "backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.running_var", "backbone_net.SA_modules.1.mlps.0.layer0.conv.weight", "backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.weight", "backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.bias", "backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.running_mean", "backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.running_var", "backbone_net.SA_modules.1.mlps.0.layer1.conv.weight", "backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.weight", "backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.bias", "backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.running_mean", "backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.running_var", "backbone_net.SA_modules.1.mlps.0.layer2.conv.weight", "backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.weight", "backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.bias", "backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.running_mean", "backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.running_var", "backbone_net.SA_modules.2.mlps.0.layer0.conv.weight", "backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.weight", "backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.bias", "backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.running_mean", "backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.running_var", "backbone_net.SA_modules.2.mlps.0.layer1.conv.weight", "backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.weight", "backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.bias", "backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.running_mean", "backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.running_var", "backbone_net.SA_modules.2.mlps.0.layer2.conv.weight", "backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.weight", "backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.bias", "backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.running_mean", "backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.running_var", "backbone_net.cov_final.weight", "backbone_net.cov_final.bias", "mlp.layer0.conv.weight", "mlp.layer0.normlayer.bn.weight", "mlp.layer0.normlayer.bn.bias", "mlp.layer0.normlayer.bn.running_mean", "mlp.layer0.normlayer.bn.running_var", "mlp.layer1.conv.weight", "mlp.layer1.normlayer.bn.weight", "mlp.layer1.normlayer.bn.bias", "mlp.layer1.normlayer.bn.running_mean", "mlp.layer1.normlayer.bn.running_var", "mlp.layer2.conv.weight", "mlp.layer2.normlayer.bn.weight", "mlp.layer2.normlayer.bn.bias", "mlp.layer2.normlayer.bn.running_mean", "mlp.layer2.normlayer.bn.running_var", "FC_layer_cla.0.conv.weight", "FC_layer_cla.0.normlayer.bn.weight", "FC_layer_cla.0.normlayer.bn.bias", "FC_layer_cla.0.normlayer.bn.running_mean", "FC_layer_cla.0.normlayer.bn.running_var", "FC_layer_cla.1.conv.weight", "FC_layer_cla.1.normlayer.bn.weight", "FC_layer_cla.1.normlayer.bn.bias", "FC_layer_cla.1.normlayer.bn.running_mean", "FC_layer_cla.1.normlayer.bn.running_var", "FC_layer_cla.2.conv.weight", "FC_layer_cla.2.conv.bias", "fea_layer.0.conv.weight", "fea_layer.0.normlayer.bn.weight", "fea_layer.0.normlayer.bn.bias", "fea_layer.0.normlayer.bn.running_mean", "fea_layer.0.normlayer.bn.running_var", "fea_layer.1.conv.weight", "fea_layer.1.conv.bias", "vote_layer.0.conv.weight", "vote_layer.0.normlayer.bn.weight", "vote_layer.0.normlayer.bn.bias", "vote_layer.0.normlayer.bn.running_mean", "vote_layer.0.normlayer.bn.running_var", "vote_layer.1.conv.weight", "vote_layer.1.normlayer.bn.weight", "vote_layer.1.normlayer.bn.bias", "vote_layer.1.normlayer.bn.running_mean", "vote_layer.1.normlayer.bn.running_var", "vote_layer.2.conv.weight", "vote_layer.2.conv.bias", "vote_aggregation.mlps.0.layer0.conv.weight", "vote_aggregation.mlps.0.layer0.normlayer.bn.weight", "vote_aggregation.mlps.0.layer0.normlayer.bn.bias", "vote_aggregation.mlps.0.layer0.normlayer.bn.running_mean", "vote_aggregation.mlps.0.layer0.normlayer.bn.running_var", "vote_aggregation.mlps.0.layer1.conv.weight", "vote_aggregation.mlps.0.layer1.normlayer.bn.weight", "vote_aggregation.mlps.0.layer1.normlayer.bn.bias", "vote_aggregation.mlps.0.layer1.normlayer.bn.running_mean", "vote_aggregation.mlps.0.layer1.normlayer.bn.running_var", "vote_aggregation.mlps.0.layer2.conv.weight", "vote_aggregation.mlps.0.layer2.normlayer.bn.weight", "vote_aggregation.mlps.0.layer2.normlayer.bn.bias", "vote_aggregation.mlps.0.layer2.normlayer.bn.running_mean", "vote_aggregation.mlps.0.layer2.normlayer.bn.running_var", "FC_proposal.0.conv.weight", "FC_proposal.0.normlayer.bn.weight", "FC_proposal.0.normlayer.bn.bias", "FC_proposal.0.normlayer.bn.running_mean", "FC_proposal.0.normlayer.bn.running_var", "FC_proposal.1.conv.weight", "FC_proposal.1.normlayer.bn.weight", "FC_proposal.1.normlayer.bn.bias", "FC_proposal.1.normlayer.bn.running_mean", "FC_proposal.1.normlayer.bn.running_var", "FC_proposal.2.conv.weight", "FC_proposal.2.conv.bias". 

Unexpected key(s) in state_dict: "module.backbone_net.SA_modules.0.mlps.0.layer0.conv.weight", "module.backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.weight", "module.backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.bias", "module.backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.running_mean", "module.backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.running_var", "module.backbone_net.SA_modules.0.mlps.0.layer0.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.0.mlps.0.layer1.conv.weight", "module.backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.weight", "module.backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.bias", "module.backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.running_mean", "module.backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.running_var", "module.backbone_net.SA_modules.0.mlps.0.layer1.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.0.mlps.0.layer2.conv.weight", "module.backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.weight", "module.backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.bias", "module.backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.running_mean", "module.backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.running_var", "module.backbone_net.SA_modules.0.mlps.0.layer2.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.1.mlps.0.layer0.conv.weight", "module.backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.weight", "module.backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.bias", "module.backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.running_mean", "module.backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.running_var", "module.backbone_net.SA_modules.1.mlps.0.layer0.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.1.mlps.0.layer1.conv.weight", "module.backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.weight", "module.backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.bias", "module.backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.running_mean", "module.backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.running_var", "module.backbone_net.SA_modules.1.mlps.0.layer1.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.1.mlps.0.layer2.conv.weight", "module.backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.weight", "module.backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.bias", "module.backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.running_mean", "module.backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.running_var", "module.backbone_net.SA_modules.1.mlps.0.layer2.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.2.mlps.0.layer0.conv.weight", "module.backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.weight", "module.backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.bias", "module.backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.running_mean", "module.backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.running_var", "module.backbone_net.SA_modules.2.mlps.0.layer0.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.2.mlps.0.layer1.conv.weight", "module.backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.weight", "module.backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.bias", "module.backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.running_mean", "module.backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.running_var", "module.backbone_net.SA_modules.2.mlps.0.layer1.normlayer.bn.num_batches_tracked", "module.backbone_net.SA_modules.2.mlps.0.layer2.conv.weight", "module.backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.weight", "module.backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.bias", "module.backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.running_mean", "module.backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.running_var", "module.backbone_net.SA_modules.2.mlps.0.layer2.normlayer.bn.num_batches_tracked", "module.backbone_net.cov_final.weight", "module.backbone_net.cov_final.bias", "module.mlp.layer0.conv.weight", "module.mlp.layer0.normlayer.bn.weight", "module.mlp.layer0.normlayer.bn.bias", "module.mlp.layer0.normlayer.bn.running_mean", "module.mlp.layer0.normlayer.bn.running_var", "module.mlp.layer0.normlayer.bn.num_batches_tracked", "module.mlp.layer1.conv.weight", "module.mlp.layer1.normlayer.bn.weight", "module.mlp.layer1.normlayer.bn.bias", "module.mlp.layer1.normlayer.bn.running_mean", "module.mlp.layer1.normlayer.bn.running_var", "module.mlp.layer1.normlayer.bn.num_batches_tracked", "module.mlp.layer2.conv.weight", "module.mlp.layer2.normlayer.bn.weight", "module.mlp.layer2.normlayer.bn.bias", "module.mlp.layer2.normlayer.bn.running_mean", "module.mlp.layer2.normlayer.bn.running_var", "module.mlp.layer2.normlayer.bn.num_batches_tracked", "module.FC_layer_cla.0.conv.weight", "module.FC_layer_cla.0.normlayer.bn.weight", "module.FC_layer_cla.0.normlayer.bn.bias", "module.FC_layer_cla.0.normlayer.bn.running_mean", "module.FC_layer_cla.0.normlayer.bn.running_var", "module.FC_layer_cla.0.normlayer.bn.num_batches_tracked", "module.FC_layer_cla.1.conv.weight", "module.FC_layer_cla.1.normlayer.bn.weight", "module.FC_layer_cla.1.normlayer.bn.bias", "module.FC_layer_cla.1.normlayer.bn.running_mean", "module.FC_layer_cla.1.normlayer.bn.running_var", "module.FC_layer_cla.1.normlayer.bn.num_batches_tracked", "module.FC_layer_cla.2.conv.weight", "module.FC_layer_cla.2.conv.bias", "module.fea_layer.0.conv.weight", "module.fea_layer.0.normlayer.bn.weight", "module.fea_layer.0.normlayer.bn.bias", "module.fea_layer.0.normlayer.bn.running_mean", "module.fea_layer.0.normlayer.bn.running_var", "module.fea_layer.0.normlayer.bn.num_batches_tracked", "module.fea_layer.1.conv.weight", "module.fea_layer.1.conv.bias", "module.vote_layer.0.conv.weight", "module.vote_layer.0.normlayer.bn.weight", "module.vote_layer.0.normlayer.bn.bias", "module.vote_layer.0.normlayer.bn.running_mean", "module.vote_layer.0.normlayer.bn.running_var", "module.vote_layer.0.normlayer.bn.num_batches_tracked", "module.vote_layer.1.conv.weight", "module.vote_layer.1.normlayer.bn.weight", "module.vote_layer.1.normlayer.bn.bias", "module.vote_layer.1.normlayer.bn.running_mean", "module.vote_layer.1.normlayer.bn.running_var", "module.vote_layer.1.normlayer.bn.num_batches_tracked", "module.vote_layer.2.conv.weight", "module.vote_layer.2.conv.bias", "module.vote_aggregation.mlps.0.layer0.conv.weight", "module.vote_aggregation.mlps.0.layer0.normlayer.bn.weight", "module.vote_aggregation.mlps.0.layer0.normlayer.bn.bias", "module.vote_aggregation.mlps.0.layer0.normlayer.bn.running_mean", "module.vote_aggregation.mlps.0.layer0.normlayer.bn.running_var", "module.vote_aggregation.mlps.0.layer0.normlayer.bn.num_batches_tracked", "module.vote_aggregation.mlps.0.layer1.conv.weight", "module.vote_aggregation.mlps.0.layer1.normlayer.bn.weight", "module.vote_aggregation.mlps.0.layer1.normlayer.bn.bias", "module.vote_aggregation.mlps.0.layer1.normlayer.bn.running_mean", "module.vote_aggregation.mlps.0.layer1.normlayer.bn.running_var", "module.vote_aggregation.mlps.0.layer1.normlayer.bn.num_batches_tracked", "module.vote_aggregation.mlps.0.layer2.conv.weight", "module.vote_aggregation.mlps.0.layer2.normlayer.bn.weight", "module.vote_aggregation.mlps.0.layer2.normlayer.bn.bias", "module.vote_aggregation.mlps.0.layer2.normlayer.bn.running_mean", "module.vote_aggregation.mlps.0.layer2.normlayer.bn.running_var", "module.vote_aggregation.mlps.0.layer2.normlayer.bn.num_batches_tracked", "module.FC_proposal.0.conv.weight", "module.FC_proposal.0.normlayer.bn.weight", "module.FC_proposal.0.normlayer.bn.bias", "module.FC_proposal.0.normlayer.bn.running_mean", "module.FC_proposal.0.normlayer.bn.running_var", "module.FC_proposal.0.normlayer.bn.num_batches_tracked", "module.FC_proposal.1.conv.weight", "module.FC_proposal.1.normlayer.bn.weight", "module.FC_proposal.1.normlayer.bn.bias", "module.FC_proposal.1.normlayer.bn.running_mean", "module.FC_proposal.1.normlayer.bn.running_var", "module.FC_proposal.1.normlayer.bn.num_batches_tracked", "module.FC_proposal.2.conv.weight", "module.FC_proposal.2.conv.bias". 

Process finished with exit code 1

I would appreciate it if you could reply. Thank you!

**Comment by freshwk** [comment]
sloved！You must have 2 GPUS to test the code.
